# Site settings
title: Flexible Grid System
description: Flexible Grid System is a Responsive CSS Framework. This framework will let you create your web applications in a flexible way that you've never experienced before.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://flexible.gs" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
